name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install fontconfig libfreetype6 libfreetype-dev libx11-dev
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: st
        path: st
